//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLkho
{
    using System;
    using System.Collections.Generic;
    
    public partial class report
    {
        public string sohd { get; set; }
        public string mavt { get; set; }
        public string barcodenhap { get; set; }
        public int slnhap { get; set; }
        public string dvt { get; set; }
        public System.DateTime ngaynhap { get; set; }
        public string manv { get; set; }
        public string dvgiaonhan { get; set; }
        public string ghichu { get; set; }
    }
}
